version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 6432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
